config/routes.rb
Rails.application.routes.draw do
  resources :competences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competence.rb
class Competence < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController
  before_action :find_competence, only: [:show, :edit, :update, :destroy]

  def index
    @competences = Compentece.all
  end

  def show
  end

  def new
    @competence = Competence.new
  end

  def create
    @competence = Competence.new(competence_path)
    redirect_to competences_path(@competence), notice: "Создали компетенцию!"
  end

  def edit
    redirect_to competences_path(@competence), notice: "Отредактировали компетенцию!"
  end

  # TODO: обработка ошибок
  def update
    @competence = Competence.update(competence_params)
    redirect_to competences_path, notice: "Удалили компетенцию!"
  end

  # TODO: обработка ошибок
  def destroy
    @competence.destroy
    render plain: "Удалили"
  end

  private
    def competence_params
      params.require(:competence).permit(:title, :description)
    end

  def find_competence
    @competence = Competence.first()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
end

app/views/competences/_form.html.haml
= form_with(model: @competenceь, local: true) do |form|
  = form.label :title, "Заголовок"
  = form.text_field :title, class: 'form-control'
  %br
  = form.label :description
  = form.text_area :description
  %br
    = form.submit nil, class: 'btn btn-success'

app/views/competences/edit.html.haml
%h2 Редактирование компетенции
= render 'form'

app/views/competences/index.html.haml
%table
  %thead
    %tr
      %th N
      %th Название
      %th Действия
  %tbody
    - @competences.each do |competence|
      %tr
        %td =competence.id
        %td =link_to competence.title, competences_path(competence)
        %td
          = link_to 'Редактировать', edit_competence_path(competence)
          = link_to 'Удалить', competence_path(competence), method: :delete, data: { confirm: "Вы уверены?"}

app/views/competences/new.html.haml
%h2 Редактирование компетенции
= render 'form'

app/views/competences/show.html.haml
%h2= @competence.title
%strong Описание
%p= @competence.description

app/views/layouts/_flashes.html.haml
.alest.alert-info= notice

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfportTrain</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flashes" %>
    <%= yield %>
  </body>
</html>